### Get all orders
GET https://localhost:7171/api/order
Content-Type: application/json

###

### Get an order by ID
GET https://localhost:7171/api/order/1
Content-Type: application/json

###

### Create a new order
POST https://localhost:7171/api/Order
Content-Type: application/json

{
  "productName": "Prduct B",
  "quantity": 1,
  "price": 100
}

###

### Update an existing order
PUT https://localhost:7171/api/order/1
Content-Type: application/json

{
  "orderId": 1,
  "productName": "string BBB",
  "quantity":5,
  "price": 55
}

###

### Delete an order
DELETE https://localhost:7171/api/order/2
Content-Type: application/json

###
